CREATE TABLE buildings (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(100) NOT NULL UNIQUE,
      number_of_floors INT NOT NULL,
      CONSTRAINT chk_building_floors
         CHECK (number_of_floors Between 1 and 200)
);
CREATE TABLE equipment (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code VARCHAR(50) NOT NULL UNIQUE ,
      label VARCHAR(100) NOT NULL
 );
CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name VARCHAR(100) NOT NULL UNIQUE ,
    building_id BIGINT NOT NULL ,
    floor INT NOT NULL ,
    capacity INT NOT NULL ,
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    FOREIGN KEY (building_id) REFERENCES buildings(id),
    CHECK ( floor >=0 ),
    CHECK ( capacity > 0 ),
    CHECK ( status IN ('AVAILABLE','MAINTENANCE') )
);
CREATE TABLE room_equipment (
    room_id BIGINT NOT NULL,
    equipment_id BIGINT NOT NULL,
    PRIMARY KEY (room_id,equipment_id),
    FOREIGN KEY (room_id) REFERENCES  rooms(id),
    FOREIGN KEY (equipment_id) REFERENCES  equipment(id)
);
CREATE TABLE organizers(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name VARCHAR(150) NOT NULL ,
    email VARCHAR(254) NOT NULL UNIQUE,
    building_id BIGINT NOT NULL ,
    floor INT NOT NULL ,
    FOREIGN KEY (building_id) REFERENCES buildings(id),
    CHECK ( floor >=0 )
);
CREATE TABLE reservations(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    title VARCHAR(200) NOT NULL ,
    room_id BIGINT NOT NULL ,
    organizer_id BIGINT NOT NULL ,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL ,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL ,
    number_of_participants INT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'CONFIRMED',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (room_id) REFERENCES  rooms(id),
    FOREIGN KEY (organizer_id) REFERENCES  organizers(id),
    CHECK ( number_of_participants > 0 ),
    CHECK ( start_time < end_time )
);
CREATE TABLE reservation_required_equipment (
    reservation_id BIGINT NOT NULL ,
    equipment_id BIGINT NOT NULL ,
    PRIMARY KEY (reservation_id, equipment_id),
    FOREIGN KEY (reservation_id) REFERENCES reservations(id),
    FOREIGN KEY (equipment_id) REFERENCES equipment(id)
);